
stages:
  - test
  - build


.playwright_job:
  stage: test
  image: mcr.microsoft.com/playwright:v1.20.0-focal
  when: manual
  script:
    - npm install
    - npx playwright install          
    - npx playwright test tests/specs$TEST_FILE --project=stage


gui-test-all:
  extends:
  - .playwright_job
  variables:
    TEST_FILE: /

gui-test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.20.0-focal 
  only:
    - master
  script:
    - npm ci
    - npx playwright install          
    - npx playwright test tests/specs --project=stage
  #artifacts:
  #  expire_in: 30 days
  #  when: always
  #  paths:
  #    - reports




